### ISSUE TITLE
ngeoDecorate*: two way binding ?

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#101]
For now, the `ngeoDecorate*` services offer a one way binding (angular to ol3).
Is it planned to have a two way binding (ol3 to angular) ?

**Comment by elemoine** [comment]
@fredj, I guess making this work would just require triggering a digest cycle when the ol3 property changes. For example, this is what the `ngeoDecorateLayer` would do for the `visible` property:

```js
    goog.events.listen(layer, ol.Object.getChangeEventType('visible'),
        /**
         * @type {ol.ObjectEvent} e Object event.
         */
        function(e) {
            $rootScope.$digest();
        }, false, this);
```

As I said, we'd need to be careful for the view center, because we don't want to trigger a digest every time the center changes while dragging the map.

What we could possibly do is add a `boolean` option/argument to the `ngeoDecorate*` functions.

**Comment by elemoine** [comment]
Closing this for now.
