### ISSUE TITLE
Adding vertex to geometry should work with virtual vertices

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1091]
Currently when the user wants to add a vertex on an existing geometry (line or polygon), he moves the cursor over the line and a vertex is shown under cursor (snapped to the line). The user can click or click-drag to add and move the vertex.

This causes problems if the user wants to display the contextual (actions) menu. For a line, for example, it's impossible to display the actions menu once the feature is selected without adding an unexpected vertex.

Also on touch devices, the vertex that is supposed to be added is not visible until the user drags the line where there is no already existing vertex.

Solution: vertex to be added should be displayed as virtual vertex at the middle of each segment.
It's the solution used in a lot of online geospatial editing applications (OpenLayers2, iD editor, Google MyMaps, etc...) and it works well.

![screenshot from 2016-04-28 17 08 56](https://cloud.githubusercontent.com/assets/319774/14890739/13f93ed8-0d64-11e6-9722-00436689b393.png)

![screenshot from 2016-04-28 17 10 05](https://cloud.githubusercontent.com/assets/319774/14890743/194d0950-0d64-11e6-925c-aad9c5161fc4.png)

Note: this modify feature interaction behavior may have already been developed in OL3 or in applications using OL3. A web search may be required beforehand.

**Comment by adube** [comment]
I'm not sure I understand how this would fix the issue.  The `ol.interaction.Modify` allows vertex to be "snapped" from anywhere from the line segments.  Do you mean to only allow the snapping to occur only from the center of those segments ?  If so, this would require a change in the `ol.interaction.Modify` class itself.

I don't really like the idea, to be honest.  We limit what's currently already working.

I also asked in a very early stage if mobile devices should be supported.  I think they still shouldn't, but let's hold that thought.

Here's an alternative.  Instead of doing this, why not do:

 * right click and/or long clicks to display the menu on desktop
 * long press to display the menu on touch devices

This would select the feature as well as display the menu.  This would require less efforts and would still make the "snapping" work from anywhere.

We could still add a "middle" vertex feature per segment and render it slightly less opaque.  This would still work.

**Comment by ybolognini** [comment]
> I'm not sure I understand how this would fix the issue. The ol.interaction.Modify allows vertex to be 
> "snapped" from anywhere from the line segments. Do you mean to only allow the snapping to occur 
> only from the center of those segments ? If so, this would require a change in the ol.interaction.Modify
> class itself.

There would be no snapping, only current vertices and virtual vertices. Actually snapping doesn't add much to the "add vertex" feature, as the goal is to move the new vertex outside of the line.

We haven't invented anything. This is the same on mymaps.google.com and in www.openstreetmap.org.

> Here's an alternative. Instead of doing this, why not do:
>     right click and/or long clicks to display the menu on desktop
>     long press to display the menu on touch devices

I don't like it. It adds one more way to interact with the geometry. But **if** it is **much** less work then I could live with a right click/long press.

> I also asked in a very early stage if mobile devices should be supported. I think they still shouldn't, but 
> let's hold that thought.

For now, edit is for desktop only. But we have to keep in mind that one day, it will certainly come to mobile.

**Comment by adube** [comment]
The behaviour you're describing would require to either change the `ol.interaction.Modify` to make it do what we want or simply create a new interaction. In both cases, my knowledge of ol3 is not high enough to accomplish this.  I'll talk to my colleages to see if one of them would be able to accomplish this.

**Comment by ybolognini** [comment]
As discussed on May 2, we put this issue in backlog and we may implement this later. 

As for the problem with contextual menu, the solution will be implemented as described in https://github.com/camptocamp/ngeo/issues/1088

**Comment by ybolognini** [comment]
Now popup menu opens on right click --> closing
