### ISSUE TITLE
Unable to select some groups

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1265]
from @vvmalbre, #1254
- https://geomapfish-demo.camptocamp.net/bl20/wsgi/mobile
- Select theme Naturgefahren
- Select group Naturgefahrenkarte

-> nothing happend, an error is displayed in the console ...

**Comment by olivierSemet** [comment]
@sbrunner  I think this is the same issue as when you try to toggle the layer "osm_time" from the "osm_function" group (in OSM theme) https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop

This is the same issue as #1248 

It's because when you toggle the state of a node "not mixed" included in a "mixed" one, the function in gmflayertree.js:

`gmf.LayertreeController.prototype.retrieveFirstParentTree_ = function(treeCtrl) {
  var tree = treeCtrl;
  while (tree.depth > 1) {
    tree = tree.parent;
  }
  return tree;
};` 

will always retrieve (independently of the node depth) the first node. If this first node is "mixed", it will be a ol.Layer.Group and therefore, there is no getSource() function attached to a layer group.

**Comment by sbrunner** [comment]
@olivierSemet if your right #1248 should be fixed in the branch 2.0 :-)

**Comment by olivierSemet** [comment]
@sbrunner I'll handle it, please change the milestone of #1248 to 2.0

**Comment by sbrunner** [comment]
done :-)

**Comment by ger-benjamin** [comment]
Thanks for the analyze @olivierSemet

**Comment by olivierSemet** [comment]
Just for information @sbrunner @ybolognini 
As the layertree changed a lot between 2.0 and 2.1, solution for 2.0 won't work for 2.1.
