### ISSUE TITLE
Draw feature example - style not correct until the feature is selected

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/ngeo#1619]
When one loads the gmf draw feature, if there are features loaded (from url or local storage), they are not styled (blue default color) until they are selected.
I think it used to work and it currently works in the desktop app though the style is applied with a little delay.

**Comment by pgiraud** [comment]
A quick git bisect told me that the guilty commit is def5a68db4e342b30db1803c25d2f29d1112fb52

**Comment by olivierSemet** [comment]
@pgiraud indeed I removed it deliberately because of the weird effect when area are displayed on features. Now with this PR, the user will see quickly the area text formatted without the good local and then the good one (e.g `1,500 km` -> `1 500 km`). It happens quickly (less than 1 second) but I found it disturbing.

**Comment by sbrunner** [comment]
As I see it steel working, not?
