### ISSUE TITLE
We can't print drawing...

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1760]
The style 
```json
 "fontSize": "10pt"
```

Creates the print error:
```
java.lang.NumberFormatException: For input string: "10pt"
```

**Comment by adube** [comment]
It would seem that GeoMapFish expects a numeric value for the font size. In the draw tools, we currently use a string value, i.e. `"10pt"`.  We can change this value to be numeric instead.

@sbrunner : Before doing that, I need to know: what is the format used by the GMF print service?  I.e.: px? pt?

Note: This change will break the exiting links were the `pt` value was used, but since GMF hasn't been officially released yet then there is no need to be retro-compatible.  In other words, people might end up loading broken links and would need to clean their browser cache and reload the page without using the full url where the `pt` is used.

**Comment by sbrunner** [comment]
It's in 'px' (should be @ 72 dpi) :-)

**Comment by sbrunner** [comment]
It's in 'px' (should be @ 72 dpi) :-) (We can specify the unit but only px is supported.)

**Comment by adube** [comment]
Understood, thanks.  I'm able to work on this, now.

**Comment by adube** [comment]
I noticed something.  When using pixels, the value sent is `10px`.  Therefore, there has to be something on the server-side that converts the `10px` string into 10 and use it as pixel value.  The `10pt` is simply not managed.

You said that we could specify the unit.  Would it make more sense to simply support `pt` on the server-side?  That way, we would keep the retro-compatibility.

I'd be in favor of this.

@sbrunner Thoughts?

**Comment by sbrunner** [comment]
Good suggestion, I will think about it :-)

**Comment by adube** [comment]
Great.  Let me know of your final decision for me to go with my original plan or not.
