### ISSUE TITLE
Redirect to desktop message

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#2354]
Where is the redirect to desktop message? Like it was in 1.6 with a tablet:

> Vous utilisez la version pour mobile. Vous pouvez aussi consulter la version standard.

**Comment by sbrunner** [comment]
Not sure the it will be created ...

**Comment by gnerred** [comment]
This message is important. If not, the user will not be able to open desktop application on a tablet.

**Comment by sbrunner** [comment]
We should probably use the screen width > 750

**Comment by sbrunner** [comment]
and height > 500 (or > 750?)

**Comment by gnerred** [comment]
The redirect message does not work on my 2.1.2.dev3 version : 
https://preprod.cartoriviera.ch/v2/
When I click on "standard version", the mobile application is still reloaded. A configuration problem on my side or an issue ? @ger-benjamin

**Comment by ger-benjamin** [comment]
It doesn't work for me neither.
To be exact, I think that it work but the desktop.html redirect immediately to the mobile.html again. I think that because that work on a desktop device (remove the "display:none; on the div to see the redirection message on a desktop device")

It should have a "no_redirect"
to be interpreted by this line and don't do the redirection: https://github.com/camptocamp/demo_geomapfish/blob/master/demo/templates/desktop.html#L8

**Comment by rbovard** [comment]
Fixed, thanks.
