### ISSUE TITLE
"make dist" error

### ISSUE THREAD

**Issue by fredj** [camptocamp/ngeo#3125]
from https://github.com/camptocamp/ngeo/pull/3098#issuecomment-345714018:
```
info ol Parsing dependencies
info ol Compiling 545 sources
ERR! compile /tmp/exports1171020-27155-aii70r.7wseomvx6r.js:12395: ERROR - Property feature never defined on ol.source.Vector.Event.prototype
ERR! compile     ol.source.Vector.Event.prototype.feature);
ERR! compile                                      ^^^^^^^
ERR! compile 
ERR! compile 1 error(s), 0 warning(s), 97.3% typed
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
```

**Comment by romanzoller** [comment]
I have tried to understand/fix this, but without success so far.

As far as I understand, this temporary file mentioned in the error message is the file generated by the `generate-exports` script. There is nothing obviously wrong with exporting`ol.source.Vector.Event.prototype.feature`, since it actually exists, but for some reason the compiler says it doesn't.

When changing the code in `ol/source/vector.js` from

```
ol.source.Vector.Event = function(type, opt_feature) {

  ol.events.Event.call(this, type);

  /**
   * The feature being added or removed.
   * @type {ol.Feature|undefined}
   * @api
   */
  this.feature = opt_feature;

};
ol.inherits(ol.source.Vector.Event, ol.events.Event);
```

to

```
ol.source.Vector.Event = function(type, opt_feature) {

  ol.events.Event.call(this, type);

  /**
   * The feature being added or removed.
   * @type {ol.Feature}
   * @api
   */
  this.feature = opt_feature || new ol.Feature();

};
ol.inherits(ol.source.Vector.Event, ol.events.Event);
```

the error goes away, but I don't really understand why. I have also tried to set other compiler flags like `"use_types_for_optimization": false` but without any success.

**Comment by gberaudo** [comment]
@romanzoller, is the file required in the exports file?

**Comment by romanzoller** [comment]
Yes, see full file [here](https://gist.github.com/romanzoller/ee1f3dd6f7d5a82d06f443c096e65ac8)

**Comment by fredj** [comment]
not relevant anymore after webpack migration
