### ISSUE TITLE
Mobile interface is unusable with tablets and 3+ layergroups enabled

### ISSUE THREAD

**Issue by rbovard** [camptocamp/ngeo#3279]
Project:

* Host: geomapfish-demo.camptocamp.net
* GeoMapFish version: 2.2

[Permalink directly where we can reproduce the issue](https://geomapfish-demo.camptocamp.net/2.2/mobile/theme/Demo?lang=fr&baselayer_ref=OSM%20map&tree_group_opacity_Group=0.65&tree_enable_osm_scale&tree_group_layers_Layers&tree_group_layers_Group=osm&tree_group_layers_OSM%20functions=Layer%20with%20very%20very%20very%20very%20very%20long%20name&tree_group_layers_External&tree_enable_osm_open=true&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_OSM%20map&tree_enable_osm_time_r_dp_2&tree_group_layers_Filters&map_x=533603&map_y=152745&map_zoom=5&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name=true&tree_enable_osm_time_r_s&tree_enable_osm_time_v_s&tree_enable_osm_time_v_dp&tree_enable_osm_time_r_dp&tree_enable_osm_time_r_year_mounth&tree_enable_osm_time_d_year_mounth&tree_enable_osm_time_r_mounth_year&tree_enable_osm_time_v_mounth_year&tree_enable_long%20wms-t%20layer%20name%20name%20name%20name%20name%20name%20name&tree_enable_two_layers=true&tree_enable_ch.astra.ausnahmetransportrouten=true&tree_enable_no_wfs=true&theme=Demo&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CFilters%20mixed%2CFilters)

Steps to reproduce the issue:
* Open this permalink with a tablet
* Try to navigate...

Result:
* Interface is unusable 

Expected result:
* Interface is usable 

The issue concern the following environment:
* Galaxy Tab S 10.5 (Android 6.0.1)
  * Chrome
  * Native browser

Notes:
* It's depending on number of layergroups (not on number of layers), because 1 layergroup = 1 WMS GetMap
* My Chrome issue #2377 was mostly concerning smartphones, so 4-5 layergroups were fine. In this current issue, it's unusable for **tablets with 3 layergroups** and not only with Chrome...
* So I don't know if it's related to the big images returned (HighDPI) see #2654 --> Is there a way to make smaller WMS queries to confirm that?

**Comment by sbrunner** [comment]
I just tested with:
* 15 layers on Chrome on Android 5.0.2 - Samsung SM-T530.
* 10 layers on Firefox on Android 5.0.2 - Samsung SM-T530.
* 15 layers on ? (Thanks apple) on ios.

And in all the cases it's not relay fluid but it's usable ...
We should continue to investigate ...

**Comment by rbovard** [comment]
This issue is related to the number of layergroups, because 1 layergoup = 1 WMS GetMap.

And you should define usable, because for me (and my users) it is not usable... ;)

First point to try, is it possible to get smaller (in px) GetMap image to confirm if it's related to the size (because it seems ok on smartphone)?

*Let me know if I can help, because it's a P1 issue for us here!*

**Comment by ybolognini** [comment]
Just had a look on our Android 5.0.2 tablet, using the exact URL that @rbovard sent.

On Firefox it isn't smooth but I confirm it is really usable. On Chrome and native browser it's more than usable, it's smooth. So I can definitely say that we cannot see the problem on this device. I'll look for an Android 6 tablet.

We may try to look for HighDPI configuration, but first we need to reproduce the problem. This is the next step. We can organize some Hangout where @rbovard could show us on his tablet (and we could show him on ours).

**Comment by fredj** [comment]
I've done some performances profiling on the Galaxy Tab S 10.5 tablet and the issue is related to the GPU on this device.

When the number of layer is low, all the images are stored into the GPU memory and the drawing time is fast. But at a certain point, the memory is full and some images are not stored into the memory but kept on the disk: the decoding of the images goes from ~10ms to ~300ms. The map is frozen.

One solution is to reduce the images size by not using the highDPI option, using this option make the [demo link](https://geomapfish-demo.camptocamp.net/2.2/mobile/theme/Demo?lang=fr&baselayer_ref=OSM%20map&tree_group_opacity_Group=0.65&tree_enable_osm_scale&tree_group_layers_Layers&tree_group_layers_Group=osm&tree_group_layers_OSM%20functions=Layer%20with%20very%20very%20very%20very%20very%20long%20name&tree_group_layers_External&tree_enable_osm_open=true&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung&tree_enable_OSM%20map&tree_enable_osm_time_r_dp_2&tree_group_layers_Filters&map_x=533603&map_y=152745&map_zoom=5&tree_enable_Layer%20with%20very%20very%20very%20very%20very%20long%20name=true&tree_enable_osm_time_r_s&tree_enable_osm_time_v_s&tree_enable_osm_time_v_dp&tree_enable_osm_time_r_dp&tree_enable_osm_time_r_year_mounth&tree_enable_osm_time_d_year_mounth&tree_enable_osm_time_r_mounth_year&tree_enable_osm_time_v_mounth_year&tree_enable_long%20wms-t%20layer%20name%20name%20name%20name%20name%20name%20name&tree_enable_two_layers=true&tree_enable_ch.astra.ausnahmetransportrouten=true&tree_enable_no_wfs=true&theme=Demo&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CFilters%20mixed%2CFilters) perfectly usable.

**Comment by fredj** [comment]
See #3389

**Comment by rbovard** [comment]
Cool, thanks a lot @fredj! I'm looking forward to test it :)

*BTW I was not wrong with this highDPI thing...*

**Comment by rbovard** [comment]
@sbrunner Is there a link where I can test with `mapPixelRatio: 1`?

**Comment by fredj** [comment]
@rbovard you can test it here: https://camptocamp.github.io/ngeo/2.2/examples/contribs/gmf/apps/mobile_alt/

**Comment by rbovard** [comment]
Thanks a lot, that's much better now!! *(I tested with the master version this morning on gh.io and was affraid to see no difference...)*

So next step is to roll out a 2.2.2 :)
