### ISSUE TITLE
Logout with intranet detection (2.2.2)

### ISSUE THREAD

**Issue by svagap** [camptocamp/ngeo#3490]
We updated our application to 2.2.2.

We have configured our environment so that user are "auto detected" according to ip adresses. This works fine. 

But if a "auto logged in" user uses the button "logout" it is logged out (good) but a page refresh is done -> so after the page is reloaded, the user is logged in as "intranet" again. (bad)

**Comment by jwkaltz** [comment]
I have talked to Peter about this, and this is a big problem for this use case:
- prior to 2.2.2, when the user clicks on logout, the user is logged out and can then re-login with a specific user id. This is needed for the user to get the correct rights for certain functionalities.
- since 2.2.2, when the user clicks on logout, an automatic refresh happens, so the user is automatically logged in as "intranet" again. So the user never gets a chance to login with his specific user id.

**Comment by pfirpfel** [comment]
Fixed in 2.2-branch with 9360ebfa8ea427b2a0c0c35b8ce606761512f16e

**Comment by jwkaltz** [comment]
@svagap you can now test this with the ngeo commit mentioned by Michael (we tested it on our test server, and it worked for us). Please note that you need to provide an additional configuration for this to work. The updated instructions regarding intranet user detection are here: https://confluence.camptocamp.com/confluence/display/GeoSupport/GMF+Intranet+Users
