### ISSUE TITLE
Disclaimer is not translated

### ISSUE THREAD

**Issue by svades** [camptocamp/ngeo#3516]
Project:

* GitHub URL: https://github.com/camptocamp/baselstadt_mapbs
* GeoMapFish version: 2.2.2

Permalink directly where we can reproduce the issue:
http://map.geo.test.bs.ch/ngeodesktop?lang=de&baselayer_ref=Grundkarte%20grau&tree_groups=Allmendbewilligungen%2CAufgrabungssperren%2CBodenbedeckung%2C%C3%96ffentlicher%20Raum%2CPermanente%20Verleihungen%20im%20%C3%B6ffentlichen%20Raum

Steps to reproduce the issue:

* open the permalink
* change language to english or french

Result: The disclaimer is not translated (see screenshot)
![disclaimer](https://user-images.githubusercontent.com/22655359/36192938-1ba3f960-1164-11e8-9d22-5084ee248130.PNG)

Expected result: The disclaimer should be translated

**Comment by llienher** [comment]
@ybolognini Currently the visible disclaimer comes from the metadata 'disclaimer' in the database. This is a single value that is always displayed, whatever the language loaded is. We should improve it to fetch the attributes to list the disclaimer value in the .po file. This would allow to override it with language.
The script has to be updated for this use case.

In the front-end we should add 'translate' to the span and makes sure that the disclaimer is generated with correct translation. 
When testing, we need to take into account projects that allow to change language from UI, probably need to destroy to current object to rebuild it with the selected language. Otherwise it would probably just not change the disclaimer on-the-fly.

**Comment by sbrunner** [comment]
fixed by https://github.com/camptocamp/c2cgeoportal/pull/3709
