### ISSUE TITLE
Layertree and tool buttons not working on iOS 7/8

### ISSUE THREAD

**Issue by eleu** [camptocamp/ngeo#838]
https://geomapfish-demo.camptocamp.net/2.0/mobile

The buttons to open layertree resp. tools show no action except turning the mapwindow grey and inactive. The map window does not move to either side to reveal the desired menus.

Observed iOS 8 and iOS9 (and on native browser on Android 4.4).

Reproducible on Browserstack, with iPhone 6Plus, iPhone 6 and iPhone 5S (as well as Samsung S5 native Browser). Works fine for iOS 9 (f.e. iPhone 6S).

![image](https://cloud.githubusercontent.com/assets/1632411/13570202/2764b7c4-e46d-11e5-8d4d-9abee77f464c.png)

**Comment by fredj** [comment]
Works fine with Chrome on Android 6.0

**Comment by pgiraud** [comment]
This may not be relevant anymore.

**Comment by olivierSemet** [comment]
This is because the online version of the mobile gmf 2.0 app does not reflect the current gmf version (included in ngeo contribs). 
The online version does not contain in css classes _.nav-left-is-visible_  and _.nav-right-is-visible_ the prefixed version of _transform_ (-webkit-transform). Therefor the transformation is just ignored by the iOS browser .

This have been fixed by @pgiraud in the ngeo MakeFile. CSS Prefix are now automatically added during the compilation process of less files by adding the arg  _--autoprefix_ to the command _lessc_ (cf Makefile line 627)

@sbrunner : I don't know if there is something to do on c2Cgeoportal as well ?

**Comment by sbrunner** [comment]
Effectively, yes :-)
