### ISSUE TITLE
Changing URL when a theme is selected breaks the variable baseTemplateUrl

### ISSUE THREAD

**Issue by olivierSemet** [camptocamp/ngeo#974]
The theme selector directive adds some pieces to the URL (e.g /contribs/gmf/apps/desktop/**_theme/OSM_**)

Therefore the variable gmf.baseTemplateUrl defined in _contribs/gmf/apps/mobile/default.js_ or _contribs/gmf/apps/desktop/default.js_ will point to a wrong path after the theme selector directive declaration. 

Could we consider to use HTML history API with the hash key in order to keep the default base URL clean?

**Comment by sbrunner** [comment]
> Could we consider to use HTML history API with the hash key in order to keep the default base URL clean?

No for backward compatibility with GeoMapFish 1.6.

**Comment by olivierSemet** [comment]
Ok, but this is not compatible with the Angular directive system. One solution, use ngTemplate to cache all partials HTML templates during the compilation time

**Comment by tsauerwein** [comment]
In https://github.com/camptocamp/ngeo/issues/520 we thought about adding a flag `gmfUrl` to the theme selector. For development and the demos on gh-pages, which do not work properly with the current url scheme, the theme selector would generate normal urls that do not break the browser navigation.
And in GMF you would set this flag, so that the urls which require Apache rewrite rules are used.

**Comment by sbrunner** [comment]
@olivierSemet It's already done ...

**Comment by olivierSemet** [comment]
Ok I close this issue,  topic is already treated #520
